//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMyselfToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.CommonDictionaries = new HashSet<CommonDictionary>();
            this.Tests = new HashSet<Test>();
            this.Sections = new HashSet<Section>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<CommonDictionary> CommonDictionaries { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
