//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMyselfToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedTest
    {
        public long Id { get; set; }
        public long TestId { get; set; }
        public long RelatedTestId { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Test Test1 { get; set; }
    }
}
