//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMyselfToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestStat
    {
        public long Id { get; set; }
        public long TestId { get; set; }
        public Nullable<int> TestUsage { get; set; }
        public Nullable<decimal> TestRating { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
