//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMyselfToday.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public long Id { get; set; }
        public string TitleText { get; set; }
        public string ResultText { get; set; }
        public string ResultDetail { get; set; }
        public string ImagePath { get; set; }
        public long TestId { get; set; }
        public int RangeStart { get; set; }
        public int RangeEnd { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
